apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: mashaya
    repository: jx3-k8s
  - key: staging
  - key: production
  - key: dev1
    owner: mashaya
    repository: jx3-k22s
  ingress:
    domain: prod.jx.nile-global.cloud
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: mayasnayak
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
